apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Govindpsd/api-monitoring-platform.git
    targetRevision: HEAD
    path: deployments/k8s/argocd/api-monitoring-app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api-monitoring
